version: '3'

services:
  next:
    build:
      context: .
      dockerfile: ./apps/next/Dockerfile
    command: bash -c "pnpm run build:next && pnpm run start:next"
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - strapi

  strapi:
    build:
      context: .
      dockerfile: ./apps/strapi/Dockerfile
    command: bash -c "pnpm run build:strapi && NODE_ENV=production pnpm run start:strapi"
    restart: always
    network_mode: host
    volumes:
      - ./apps/strapi/public/uploads:/sizov/apps/strapi/public/uploads
