version: '3'

services:
  next:
    build:
      context: .
      dockerfile: ./apps/next/Dockerfile
    command: bash -c "pnpm run build:next && pnpm run start:next"
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - strapi
    volumes:
      - .:/sizov-project-2

  strapi:
    build:
      context: .
      dockerfile: ./apps/strapi/Dockerfile
    command: bash -c "pnpm run build:strapi && NODE_ENV=production pnpm run start:strapi"
    restart: always
    network_mode: host
    volumes:
      - .:/sizov-project-2
