import { Navigation, Footer } from '@/shared/components';
import './global.css';

export const metadata = {
  title: 'Welcome to app',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div className="min-h-screen bg-[#1C1C1C] text-white font-mono">
          <Navigation />

          {children}

          <Footer />
        </div>
      </body>
    </html>
  );
}
