name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build Strapi
        run: npm run build

      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Deploy to Server
        env:
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
          SERVER_IP: ${{ secrets.SERVER_IP }}
          DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
        run: |
          sshpass -p "$SERVER_PASSWORD" rsync -avz --delete-after --exclude='node_modules' --exclude='.git' ./ $SERVER_USER@$SERVER_IP:$DEPLOY_PATH
          sshpass -p "$SERVER_PASSWORD" ssh $SERVER_USER@$SERVER_IP "cd $DEPLOY_PATH && npm install --production && pm2 restart strapi || pm2 start npm --name 'strapi' -- run start"
