name: Deploy Straou to DevServer

on:
  push:
    branches:
      - ci-cd

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Add server to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.DEV_SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Pull code from branch
        run: |
          sshpass -p "${{ secrets.DEV_SERVER_PASSWORD }}" ssh -v ${{ secrets.DEV_SERVER_USER }}@${{ secrets.DEV_SERVER_IP }} "cd sizov-project-2 && git checkout main && git pull"

      - name: Install dependencies
        run: |
          sshpass -p "${{ secrets.DEV_SERVER_PASSWORD }}" ssh -v ${{ secrets.DEV_SERVER_USER }}@${{ secrets.DEV_SERVER_IP }} "source ~/.bashrc && cd sizov-project-2 && pnpm install"

      - name: Build Strapi
        run: |
          sshpass -p "${{ secrets.DEV_SERVER_PASSWORD }}" ssh -v ${{ secrets.DEV_SERVER_USER }}@${{ secrets.DEV_SERVER_IP }} "cd sizov-project-2 && pnpm run --filter strapi build"

      - name: Run Strapi
        run: |
          sshpass -p "${{ secrets.DEV_SERVER_PASSWORD }}" ssh -v ${{ secrets.DEV_SERVER_USER }}@${{ secrets.DEV_SERVER_IP }} "cd sizov-project-2 && forever start -c 'pnpm run --filter strapi start' ./"
