name: Deploy Straou to DevServer

on:
  push:
    branches:
      - ci-cd

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Build and Deploy to Server
        env:
          DEV_SERVER_USER: ${{ secrets.DEV_SERVER_USER }}
          DEV_SERVER_PASSWORD: ${{ secrets.DEV_SERVER_PASSWORD }}
          DEV_SERVER_IP: ${{ secrets.DEV_SERVER_IP }}
        run: |
          sshpass -p "$DEV_SERVER_PASSWORD" ssh $DEV_SERVER_USER@$DEV_SERVER_IP "cd sizov-project-2 && pnpm install"
          sshpass -p "$DEV_SERVER_PASSWORD" ssh $DEV_SERVER_USER@$DEV_SERVER_IP "cd sizov-project-2 && pnpm run --filter strapi build"
          sshpass -p "$DEV_SERVER_PASSWORD" ssh $DEV_SERVER_USER@$DEV_SERVER_IP "cd sizov-project-2 && forever start -c 'pnpm run --filter strapi start' ./"
