name: Deploy Straou to DevServer

on:
  push:
    branches:
      - ci-cd

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Build and Deploy to Server
        run: |
          sshpass -p "${{ secrets.DEV_SERVER_PASSWORD }}" ssh ${{ secrets.DEV_SERVER_USER }}@${{ secrets.DEV_SERVER_IP }} "cd sizov-project-2 && cat package.json"
